# Generated by Django 3.2.5 on 2021-07-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceCity', models.CharField(max_length=50)),
                ('destinationCity', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainName', models.CharField(max_length=50)),
                ('trainId', models.IntegerField()),
                ('carriages', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50)),
                ('numberOfSeats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.seats')),
            ],
        ),
    ]
