# Generated by Django 3.2.5 on 2021-07-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50, null=True),
        ),
    ]
