# Generated by Django 3.2.5 on 2021-07-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210714_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='train',
        ),
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.seats'),
        ),
    ]
