# Generated by Django 3.2.5 on 2021-07-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_train_numberofseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='train',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.IntegerField(),
        ),
    ]
