# Generated by Django 3.2.5 on 2021-07-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210714_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='train',
        ),
    ]
