# Generated by Django 3.2.5 on 2021-07-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_seats_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.seats'),
        ),
    ]
