# Generated by Django 3.2.5 on 2021-07-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210715_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='train',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50, null=True),
        ),
    ]
