# Generated by Django 3.2.5 on 2021-07-14 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210715_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.seats'),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=50, null=True),
        ),
    ]
