# Generated by Django 3.2.5 on 2021-07-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210715_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.seats'),
        ),
    ]
