# Generated by Django 3.2.5 on 2021-07-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_train_numberofseats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='active',
        ),
        migrations.RemoveField(
            model_name='train',
            name='status',
        ),
    ]
