# Generated by Django 3.2.5 on 2021-07-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210715_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='available_seats',
            field=models.IntegerField(),
        ),
    ]
