# Generated by Django 3.2.5 on 2021-07-14 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_seats_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='numberOfSeats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.seats'),
        ),
    ]
