# Generated by Django 3.2.5 on 2021-07-15 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20210715_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCity', models.CharField(max_length=50)),
                ('dCity', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seats', models.IntegerField()),
                ('tripId', models.IntegerField()),
                ('trainId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.train')),
            ],
        ),
    ]
