# Generated by Django 3.2.5 on 2021-07-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trainId',
        ),
    ]
