# Generated by Django 3.2.5 on 2021-07-15 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_trip_trainid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trainId',
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.train')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.trip')),
            ],
        ),
    ]
