# Generated by Django 3.2.5 on 2021-07-15 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20210715_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trainId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.train'),
        ),
        migrations.DeleteModel(
            name='All',
        ),
    ]
