# Generated by Django 3.2.5 on 2021-07-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20210715_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trainId',
            new_name='train',
        ),
    ]
