# Generated by Django 3.2.5 on 2021-07-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_rename_trainid_trip_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='train',
        ),
        migrations.AddField(
            model_name='train',
            name='trip',
            field=models.ManyToManyField(null=True, to='pages.Trip'),
        ),
    ]
