# Generated by Django 3.2.5 on 2021-07-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20210716_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='trip',
            field=models.ManyToManyField(to='pages.Trip'),
        ),
    ]
