# Generated by Django 3.2.5 on 2021-07-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_train_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='trip',
        ),
        migrations.AddField(
            model_name='train',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.trip'),
        ),
    ]
