# Generated by Django 3.2.5 on 2021-07-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='train',
            new_name='train_id',
        ),
    ]
